print("Kenneth B. Cabodte")
print("Malusak, Boac, Marinduque")
print("June 29, 2002")
print("MSC BSI/T 2A")
print("Watching Anime")
print("Playing MOBA Game")
print("Photo Manipulation")
print("Cooking")
print("Cycling")